### ISSUE TITLE
Results Interpretation Issue

### ISSUE THREAD

**Issue by lawrencekhlim** [viktorleis/perfevent#6]
Dear Mr. Leis,

Thanks for making such a simple to use benchmarking tool! It's been really great for me to use. I just have a question about a result I am getting, particularly about "kcycles". This is some output I've received from benchmarking my code:

`   cycles, kcycles, instructions, L1-misses, LLC-misses, branch-misses, task-clock, scale,  IPC, CPUs,  GHz 
537854.93, 4405.93,   1132245.64,   1892.80,    1892.78,         40.53,  220966.03, 10000, 2.11, 0.72, 2.43
`
where cycles is reported at 537854.93 and kcycles is reported at 4405.93. I initially interpreted kcycles as kilo-cycles (or 1000 cycles); however, this does not match up with the data. Could you clarify what is meant by kcycles here?

**Comment by viktorleis** [comment]
kcycles is the number of CPU cycles in the operating system kernel. cycles includes both user and kernel space.

**Comment by lawrencekhlim** [comment]
Thank you!
