### ISSUE TITLE
"Error opening counter cycles" on AWS

### ISSUE THREAD

**Issue by lawrencekhlim** [viktorleis/perfevent#7]
Dear Dr. Viktor Leis,

I tried using your PerfEvent.hpp benchmarking tool on Amazon Web Services but was unable to get it to work with a "Error opening counter cycles" error. I even tried your suggestion of `sudo sysctl -w kernel.perf_event_paranoid=-1` under Troubleshooting in your README.md, and I still got the error. I was using Amazon Linux 2 on a t2.large machine. Do you know what might be causing the issue or if I could use a different machine / OS to get it to work?

(Before, I believe I was able to get your code to work on an Oracle Cloud machine, but unfortunately my credits have run out.)

Thanks for such a great tool!

Best,
Lawrence

**Comment by viktorleis** [comment]
Not all EC2 instances support performance counters: https://stackoverflow.com/questions/69395912/pmu-x86-64-performance-counters-not-showing-in-perf-under-aws
